include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - macros
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    todo: false
    invalid_annotation_target: ignore
    avoid_print: ignore

linter:
  rules:
    constant_identifier_names: true
    directives_ordering: true
    prefer_single_quotes: true
    require_trailing_commas: true
    lines_longer_than_80_chars: false
    always_use_package_imports: true
    prefer_const_declarations: true
    public_member_api_docs: false
    prefer_const_constructors: true
    empty_statements: true
    no_duplicate_case_values: true
    annotate_overrides: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    prefer_conditional_assignment: true
    prefer_const_literals_to_create_immutables: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    unnecessary_null_in_if_null_operators: true
    use_key_in_widget_constructors: true
    sort_constructors_first: true
    prefer_final_locals: true
    